version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: pneuscope-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: pneuscope
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - pneuscope-network

  backend:
    build: ./backend
    container_name: pneuscope-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/pneuscope?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_for_production
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:3000
      ML_SERVICE_URL: http://ml-service:5000
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
      - ml-service
    networks:
      - pneuscope-network

  ml-service:
    build: ./ml-service
    container_name: pneuscope-ml
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - pneuscope-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pneuscope-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
      NEXT_PUBLIC_ML_SERVICE_URL: http://localhost:5000
      NEXT_PUBLIC_SOCKET_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - pneuscope-network

volumes:
  mongodb_data:

networks:
  pneuscope-network:
    driver: bridge
